VARIACOES = {'Adriele': ['adrielle', 'adryele', 'adryele carneiro policarpo'],
             'Erika': ['érika mainardi', 'érika mainardi mulassani', 'érika mm', 'érika mulasani mainardi',
                       'érika mulassai mainardi', 'érika mulassani', 'érika mulassani m', 'érika mulassani mainardi',
                       'érika mulasssani mainardi'],
             'Tamires': ['tamires', 'tamires olieveira', 'tamires oliveira', 'tamires oliveira dos santos',
                         'tamires olivera', 'tamires olivereira', 'tamires oliveria', 'tamires olivira',
                         'tamires olveira', 'tamiresoliveira'],
             'Ana Camillo': ['ana camillo', 'ana camilo'],
             'Andreia Santos': ['andeia', 'andeia santos', 'andrei santos', 'andreia', 'andreia  santos',
                                'andreia dsantos', 'andreia sanmtos', 'andreia santos', 'andria  santos',
                                'andria santos', 'arian'],
             'Bianca Lemos': ['banca lemos', 'bianca', 'bianca lemos', 'binca'],
             'Bárbara': ['bárbara'],
             'Caleb': ['caaleb', 'caleb', 'caleb (atendi o cliente pois o responsável pelo atendimento ufsc estava '
                                          'em pausa. binia ciente.)', 'caleb (corrigindo', 'caleb dias'],
             'Davi': ['davi'],
             'Diana Melo': ['diana', 'diana . melo', 'diana melo', 'diana mleo', 'diana.melo'],
             'Edson Silva': ['edson silva'],
             'Eugênia': ['eugenia', 'eugénia', 'eugênia'],
             'Estela': ['eztela', 'essstelsa', 'estekla', 'estela', 'esttela', 'etsela'],
             'Franciele': ['franciele', 'francielly'],
             'Francine': ['francine', 'francine martins', 'franciny', 'franciny batista', 'franciny batista silvano',
                          'franciny silvano'],
             'Henrique D\'ávilla': ['henrique d\'ávila'],
             'Henrique Freitag': ['henrique freitag', 'henrque freitag'],
             'Hugo César da Silva': ['hugo cesar da silva'],
             'Jacqueline Lais': ['jacqueleine lais', 'jacquelien lais', 'jacqueline lais', 'jacqueline las',
                                 'jacquelne lais'],
             'Juliana': ['jualiana', 'juliana'],
             'Leonardo Eugênio Vieira': ['leonardo eugênio vieira'],
             'Lucas Lehmkuhl dos Santos': ['lucas', 'lucas lehmkuhl dos santos'],
             'Luna Castanheiro de Carvalho': ['luna castanheiro de carvalho'],
             'Mallone Almeida': ['mallone', 'mallone almeida'],
             'Marcos Stein': ['marcos stein'],
             'Marina ': ['marina', 'marina toneli siqueira (mãe de alice toneli siqueira da ros)'],
             'Matheus': ['matheus'],
             'Milenna Evellin': ['mielnna', 'miena', 'mienna', 'milena', 'milenn', 'milenna',
                                 'milenna coletivo empresarial', 'milenna evellin', 'mlenna'],
             'Natalia': ['natalia'],
             'Nicoly Lima': ['nicly lima', 'nicoly', 'nicoly lima', 'nicoy lima'],
             'Patrick Borges': ['patrick borges'],
             'Rayssa Silva de Campos': ['rayssa silva de campos'],
             'Renato': ['renato', 'renato.', 'rernato'],
             'Rômulo': ['rómulo', 'rômulo', 'rômulo', 'rõmulo', "rômulo'"],
             'Salete': ['salete julia folster schmitz'],
             'Sarah Zimmermann': ['sara', 'sara zimermann', 'sara zimmemann', 'sara zimmerman', 'sara zimmermann',
                                  'sara zimmetmann', 'sarah baracho', 'sarah moragana', 'sarah morgana',
                                  'saa zimmermann'],
             'Suzani Cassiani': ['suzani cassiani'],
             'Val': ['val'],
             'Vanessa Gallardo': ['vanesa gallardo', 'vanessa', 'vanessa galalrdo', 'vanessa gallardo',
                                  'vanessa rosa', 'vasnessa gallardo'],
             'Waldemar Bilhalva': ['waldemar', 'waldemar bilhalva']}
